repo:
  public: lua-server-sdk
  private: lua-server-sdk-private

circleci:
  linux:
    image: ubuntu:18.04

documentation:
  title: LaunchDarkly Server-Side SDK for Lua
  githubPages: true

sdk:
  displayName: "Lua (server-side)"
